# POSTTEST 7

## WANDA NURHALIZA
## 2109106055

## IMPORT LIBRARY

In [1]:
import tensorflow as tf
import numpy as np

## MEMBUAT SEBUAH TENSOR DENGAN SHAPE (5,5) DENGAN NILAI RANDOM YANG DISIMPAN DALAM VARIABLE RANDOM_TENSOR

In [2]:
random_tensor = tf.random.uniform([5,5], minval = 0, maxval = 5, dtype = tf.int32)
random_tensor.numpy()
print(random_tensor)

tf.Tensor(
[[1 0 4 3 3]
 [3 4 0 3 3]
 [0 4 1 2 3]
 [4 4 2 4 2]
 [3 0 4 1 1]], shape=(5, 5), dtype=int32)


## MEMBUAT SEBUAH TENSOR DENGAN SHAPE (5,5) DARI SEBUAH LIST DENGAN NILAI BILANGAN PRIMA DALAM VARIABLE PRIME_TENSOR

In [3]:
prime_list = [[2, 34, 5, 7, 11], [13, 17, 19, 23, 29], [31, 37, 41, 43, 47], [53, 59, 61, 67, 71], [73, 79, 83, 89, 97]]
prime_tensor = tf.convert_to_tensor(prime_list, dtype = tf.int32)
prime_tensor.numpy()
print(prime_tensor)

tf.Tensor(
[[ 2 34  5  7 11]
 [13 17 19 23 29]
 [31 37 41 43 47]
 [53 59 61 67 71]
 [73 79 83 89 97]], shape=(5, 5), dtype=int32)


## MENAMPILKAN DIMENSI DARI KEDUA VARIABLE TERSEBUT

##### MENAMPILKAN DIMENSI DARI VARIABLE RANDOM_TENSOR

In [4]:
print(random_tensor.shape)

(5, 5)


##### MENAMPILKAN DIMENSI DARI VARIABLE PRIME_TENSOR

In [5]:
print(prime_tensor.shape)

(5, 5)


## MENAMPILKAN HASIL DARI PERHITUNGAN ARITMETIKA 2 VARIABLE TERSEBUT

##### PENJUMLAHAN

In [6]:
hasil = tf.add(random_tensor, prime_tensor)
print(f'--- HASIL PENJUMLAHAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- \n {hasil}')

--- HASIL PENJUMLAHAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- 
 [[ 3 34  9 10 14]
 [16 21 19 26 32]
 [31 41 42 45 50]
 [57 63 63 71 73]
 [76 79 87 90 98]]


##### PENGURANGAN

In [7]:
hasil = tf.subtract(random_tensor, prime_tensor)
print(f'--- HASIL PENGURANGAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- \n {hasil}')

--- HASIL PENGURANGAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- 
 [[ -1 -34  -1  -4  -8]
 [-10 -13 -19 -20 -26]
 [-31 -33 -40 -41 -44]
 [-49 -55 -59 -63 -69]
 [-70 -79 -79 -88 -96]]


##### PERKALIAN

In [8]:
hasil = tf.multiply(random_tensor, prime_tensor)
print(f'--- HASIL PERKALIAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- \n {hasil}')

--- HASIL PERKALIAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- 
 [[  2   0  20  21  33]
 [ 39  68   0  69  87]
 [  0 148  41  86 141]
 [212 236 122 268 142]
 [219   0 332  89  97]]


##### PEMBAGIAN

In [9]:
hasil = tf.divide(random_tensor, prime_tensor)
print(f'--- HASIL PEMBAGIAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- \n {hasil}')

--- HASIL PEMBAGIAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- 
 [[0.5        0.         0.8        0.42857143 0.27272727]
 [0.23076923 0.23529412 0.         0.13043478 0.10344828]
 [0.         0.10810811 0.02439024 0.04651163 0.06382979]
 [0.0754717  0.06779661 0.03278689 0.05970149 0.02816901]
 [0.04109589 0.         0.04819277 0.01123596 0.01030928]]


##### PERPANGKATAN

In [10]:
hasil = tf.pow(random_tensor, prime_tensor)
print(f'--- HASIL PERPANGKATAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- \n {hasil}')

--- HASIL PERPANGKATAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- 
 [[         1          0       1024       2187     177147]
 [   1594323          0          0 -346101685 1094942099]
 [         0          0          1          0 1402212843]
 [         0          0          0          0          0]
 [1534976995          0          0          1          1]]


## MENAMPILKAN NILAI MAKSIMAL DAN MINIMAL DARI VARIABLE RANDOM_TENSOR

In [11]:
max_random_tensor = tf.argmax(random_tensor, axis = 0)
print("NILAI MAKSIMAL DARI VARIABLE RANDOM_TENSOR :", max_random_tensor.numpy())

NILAI MAKSIMAL DARI VARIABLE RANDOM_TENSOR : [3 1 0 3 0]


In [12]:
min_random_tensor = tf.argmin(random_tensor, axis = 0)
print("NILAI MINIMUM DARI VARIABLE RANDOM_TENSOR :", min_random_tensor.numpy())

NILAI MINIMUM DARI VARIABLE RANDOM_TENSOR : [2 0 1 4 4]


## MENAMPILKAN HASIL DARI PENGGABUNGAN VARIABLE RANDOM_TENSOR DENGAN PRIME_TENSOR (CONCATENATION)

In [13]:
concat = tf.concat([random_tensor, prime_tensor], axis = 0)
concat.numpy()
print(concat)

tf.Tensor(
[[ 1  0  4  3  3]
 [ 3  4  0  3  3]
 [ 0  4  1  2  3]
 [ 4  4  2  4  2]
 [ 3  0  4  1  1]
 [ 2 34  5  7 11]
 [13 17 19 23 29]
 [31 37 41 43 47]
 [53 59 61 67 71]
 [73 79 83 89 97]], shape=(10, 5), dtype=int32)


## MENAMPILKAN HASIL SORTING DARI KEDUA VARIABLE DI ATAS (DESCENDING)

##### HASIL SORTING DARI VARIABLE RANDOM_TENSOR

In [14]:
tf.sort(random_tensor, direction = "DESCENDING")

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[4, 3, 3, 1, 0],
       [4, 3, 3, 3, 0],
       [4, 3, 2, 1, 0],
       [4, 4, 4, 2, 2],
       [4, 3, 1, 1, 0]])>

##### HASIL SORTING DARI VARIABLE PRIME_TENSOR

In [15]:
tf.sort(prime_tensor, direction = "DESCENDING")

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[34, 11,  7,  5,  2],
       [29, 23, 19, 17, 13],
       [47, 43, 41, 37, 31],
       [71, 67, 61, 59, 53],
       [97, 89, 83, 79, 73]])>

##### HASIL SORTING DARI GABUNGAN KEDUA VARIABLE

In [16]:
tf.sort(concat, direction = "DESCENDING")

<tf.Tensor: shape=(10, 5), dtype=int32, numpy=
array([[ 4,  3,  3,  1,  0],
       [ 4,  3,  3,  3,  0],
       [ 4,  3,  2,  1,  0],
       [ 4,  4,  4,  2,  2],
       [ 4,  3,  1,  1,  0],
       [34, 11,  7,  5,  2],
       [29, 23, 19, 17, 13],
       [47, 43, 41, 37, 31],
       [71, 67, 61, 59, 53],
       [97, 89, 83, 79, 73]])>