# POSTTEST 7

## WANDA NURHALIZA
## 2109106055

## IMPORT LIBRARY

In [1]:
import tensorflow as tf
import numpy as np

## MEMBUAT SEBUAH TENSOR DENGAN SHAPE (5,5) DENGAN NILAI RANDOM YANG DISIMPAN DALAM VARIABLE RANDOM_TENSOR

In [2]:
random_tensor = tf.random.uniform([5,5], minval = 0, maxval = 5, dtype = tf.int32)
random_tensor.numpy()
print(random_tensor)

tf.Tensor(
[[3 1 4 2 3]
 [2 1 0 0 2]
 [4 0 1 3 4]
 [4 1 3 4 0]
 [2 4 0 3 4]], shape=(5, 5), dtype=int32)


## MEMBUAT SEBUAH TENSOR DENGAN SHAPE (5,5) DARI SEBUAH LIST DENGAN NILAI BILANGAN PRIMA DALAM VARIABLE PRIME_TENSOR

In [3]:
prime_list = [[2, 4, 6, 8, 9], [11, 13, 15, 17, 18], [20, 23, 26, 28, 30], [31, 35, 37, 39, 42], [47, 53, 39, 62, 65]]
prime_tensor = tf.convert_to_tensor(prime_list, dtype = tf.int32)
prime_tensor.numpy()
print(prime_tensor)

tf.Tensor(
[[ 2  4  6  8  9]
 [11 13 15 17 18]
 [20 23 26 28 30]
 [31 35 37 39 42]
 [47 53 39 62 65]], shape=(5, 5), dtype=int32)


## MENAMPILKAN DIMENSI DARI KEDUA VARIABLE TERSEBUT

##### MENAMPILKAN DIMENSI DARI VARIABLE RANDOM_TENSOR

In [4]:
print(random_tensor.shape)

(5, 5)


##### MENAMPILKAN DIMENSI DARI VARIABLE PRIME_TENSOR

In [5]:
print(prime_tensor.shape)

(5, 5)


## MENAMPILKAN HASIL DARI PERHITUNGAN ARITMETIKA 2 VARIABLE TERSEBUT

##### PENJUMLAHAN

In [6]:
hasil = tf.add(random_tensor, prime_tensor)
print(f'--- HASIL PENJUMLAHAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- \n {hasil}')

--- HASIL PENJUMLAHAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- 
 [[ 5  5 10 10 12]
 [13 14 15 17 20]
 [24 23 27 31 34]
 [35 36 40 43 42]
 [49 57 39 65 69]]


##### PENGURANGAN

In [7]:
hasil = tf.subtract(random_tensor, prime_tensor)
print(f'--- HASIL PENGURANGAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- \n {hasil}')

--- HASIL PENGURANGAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- 
 [[  1  -3  -2  -6  -6]
 [ -9 -12 -15 -17 -16]
 [-16 -23 -25 -25 -26]
 [-27 -34 -34 -35 -42]
 [-45 -49 -39 -59 -61]]


##### PERKALIAN

In [8]:
hasil = tf.multiply(random_tensor, prime_tensor)
print(f'--- HASIL PERKALIAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- \n {hasil}')

--- HASIL PERKALIAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- 
 [[  6   4  24  16  27]
 [ 22  13   0   0  36]
 [ 80   0  26  84 120]
 [124  35 111 156   0]
 [ 94 212   0 186 260]]


##### PEMBAGIAN

In [9]:
hasil = tf.divide(random_tensor, prime_tensor)
print(f'--- HASIL PEMBAGIAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- \n {hasil}')

--- HASIL PEMBAGIAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- 
 [[1.5        0.25       0.66666667 0.25       0.33333333]
 [0.18181818 0.07692308 0.         0.         0.11111111]
 [0.2        0.         0.03846154 0.10714286 0.13333333]
 [0.12903226 0.02857143 0.08108108 0.1025641  0.        ]
 [0.04255319 0.0754717  0.         0.0483871  0.06153846]]


##### PERPANGKATAN

In [10]:
hasil = tf.pow(random_tensor, prime_tensor)
print(f'--- HASIL PERPANGKATAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- \n {hasil}')

--- HASIL PERPANGKATAN DARI RANDOM_TENSOR DAN PRIME_TENSOR --- 
 [[          9           1        4096         256       19683]
 [       2048           1           0           0      262144]
 [          0           0           1  1796636465           0]
 [          0           1 -1565174669           0           0]
 [          0           0           0   703701817           0]]


## MENAMPILKAN NILAI MAKSIMAL DAN MINIMAL DARI VARIABLE RANDOM_TENSOR

In [11]:
max_random_tensor = tf.argmax(random_tensor, axis = 0)
print("NILAI MAKSIMAL DARI VARIABLE RANDOM_TENSOR :", max_random_tensor.numpy())

NILAI MAKSIMAL DARI VARIABLE RANDOM_TENSOR : [2 4 0 3 2]


In [12]:
min_random_tensor = tf.argmin(random_tensor, axis = 0)
print("NILAI MINIMUM DARI VARIABLE RANDOM_TENSOR :", min_random_tensor.numpy())

NILAI MINIMUM DARI VARIABLE RANDOM_TENSOR : [1 2 1 1 3]


## MENAMPILKAN HASIL DARI PENGGABUNGAN VARIABLE RANDOM_TENSOR DENGAN PRIME_TENSOR (CONCATENATION)

In [13]:
concat = tf.concat([random_tensor, prime_tensor], axis = 0)
concat.numpy()
print(concat)

tf.Tensor(
[[ 3  1  4  2  3]
 [ 2  1  0  0  2]
 [ 4  0  1  3  4]
 [ 4  1  3  4  0]
 [ 2  4  0  3  4]
 [ 2  4  6  8  9]
 [11 13 15 17 18]
 [20 23 26 28 30]
 [31 35 37 39 42]
 [47 53 39 62 65]], shape=(10, 5), dtype=int32)


## MENAMPILKAN HASIL SORTING DARI KEDUA VARIABLE DI ATAS (DESCENDING)

##### HASIL SORTING DARI VARIABLE RANDOM_TENSOR

In [14]:
tf.sort(random_tensor, direction = "DESCENDING")

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[4, 3, 3, 2, 1],
       [2, 2, 1, 0, 0],
       [4, 4, 3, 1, 0],
       [4, 4, 3, 1, 0],
       [4, 4, 3, 2, 0]])>

##### HASIL SORTING DARI VARIABLE PRIME_TENSOR

In [15]:
tf.sort(prime_tensor, direction = "DESCENDING")

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 9,  8,  6,  4,  2],
       [18, 17, 15, 13, 11],
       [30, 28, 26, 23, 20],
       [42, 39, 37, 35, 31],
       [65, 62, 53, 47, 39]])>

##### HASIL SORTING DARI GABUNGAN KEDUA VARIABLE

In [16]:
tf.sort(concat, direction = "DESCENDING")

<tf.Tensor: shape=(10, 5), dtype=int32, numpy=
array([[ 4,  3,  3,  2,  1],
       [ 2,  2,  1,  0,  0],
       [ 4,  4,  3,  1,  0],
       [ 4,  4,  3,  1,  0],
       [ 4,  4,  3,  2,  0],
       [ 9,  8,  6,  4,  2],
       [18, 17, 15, 13, 11],
       [30, 28, 26, 23, 20],
       [42, 39, 37, 35, 31],
       [65, 62, 53, 47, 39]])>